apiVersion: v1
kind: Service
metadata:
  name: unbound
  annotations:
    metallb.universe.tf/address-pool: noc-poc-pool
    # metallb.universe.tf/loadBalancerIPs: 192.168.1.53
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
