apiVersion: v1
kind: Service
metadata:
  name: dnsdist-metrics
  labels:
    app: dnsdist
    app.kubernetes.io/part-of: noc-poc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
spec:
  type: ClusterIP
  selector:
    app: dnsdist
  ports:
    - name: metrics
      port: 8083
      targetPort: 8083
      protocol: TCP
